#include "mapping_application_variables.h"

namespace Kratos
{
KRATOS_CREATE_VARIABLE(int, MAPPING_MATRIX_EQUATION_ID);
KRATOS_CREATE_VARIABLE(Vector, MAPPER_NEIGHBOR_INFORMATION);
// Variables for Debugging
KRATOS_CREATE_VARIABLE(double, NEIGHBOR_RANK);
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(NEIGHBOR_COORDINATES);
}