#include "mapping_application_variables.h"

namespace Kratos
{
KRATOS_CREATE_VARIABLE(int, MAPPING_MATRIX_EQUATION_ID);
KRATOS_CREATE_VARIABLE(int, MAPPING_MATRIX_EQUATION_ID_ORIGIN); // TODO this is temp, remove it!
KRATOS_CREATE_VARIABLE(Vector, MAPPING_MATRIX_EQUATION_ID_VECTOR);
KRATOS_CREATE_VARIABLE(double, NEIGHBOR_RANK);
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(NEIGHBOR_COORDINATES);
}